services:
  api_service:
    build: .
    restart: always
    ports:
      - "8000:8080"
    networks:
      - networkmysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/shopdb?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=nam123
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    build: .
    container_name: mysqlcontainer-num02
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    networks:
      - networkmysql
    environment:
      MYSQL_DATABASE: shopdb
      MYSQL_PASSWORD: nam123
      MYSQL_ROOT_PASSWORD: nam123
      MYSQL_NATIVE_PASSWORD: nam123
networks:
  networkmysql: