
spring:
  application:
    name: tech_shop
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb
    username: root
    password: nam123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    generate-ddl: true
#for docker deployment

#spring:
#  datasource:
#    url: jdbc:mysql://mysqldb:3306/shopdb
#    username: root
#    password: nam123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    generate-ddl: true
server:
  port: 8080


