package com.normdevstorm.never_give_up.utils;

public enum ProductTypeEnum {
    NONE,
    LAPTOP,
    DESKTOP,
    CAMERA,
    MOUSE,
    MONITOR,
    KEYBOARD,
    TABLET,
    SMARTPHONE,
    PRINTER,
    SCANNER,
    SPEAKER,
    HEADPHONES,
    MICROPHONE,
    SMARTWATCH,
    ROUTER,
    MODEM,
    HARD_DRIVE,
    SOLID_STATE_DRIVE,
    USB_DRIVE,
    MEMORY_CARD,
    PROJECTOR,
    GRAPHICS_CARD,
    MOTHERBOARD,
    CPU,
    RAM,
    POWER_SUPPLY,
    CASE_PC,
    COOLING_FAN,
    WEBCAM,
    DRONE,
    VR_HEADSET,
    GAME_CONSOLE
}
